### ISSUE TITLE
element-ui: fix ui issues (verification badges)

### ISSUE THREAD

**Issue by ifaouibadi** [superhero-com/superhero-chat-web#24]

**Comment by ifaouibadi** [comment]
- [ ]  Some of the rooms have a verified badge, and some do not:
- [ ] The rooms become verified after verified user joined the room. Is it expected? Or only users have to be verified?

**Comment by Liubov-crypto** [comment]
@ifaouibadi  In general it's fixed, but I still see some of my old rooms with verified badges...


https://github.com/superhero-com/element-web/assets/69896204/d1a71e4b-61c7-4162-baf9-da7a519c28f5

**Comment by Liubov-crypto** [comment]
The rooms becomes verified after I send an invitation to join verified users. Reproducible for private and public spaces. The same UI issue is described in #31

**Comment by Liubov-crypto** [comment]
Fixed, LGTM
