### ISSUE TITLE
0 has been added at the end of the room/community name

### ISSUE THREAD

**Issue by olszewskimar** [superhero-com/superhero-chat-web#30]
### Steps to reproduce

0 has been added at the end of the room/community name:

<img width="283" alt="Zrzut ekranu 2024-01-5 o 09 30 39" src="https://github.com/superhero-com/element-web/assets/147718725/de75bf1b-940c-461d-8b6b-2fd843d03a71">

### Outcome

Moved from -> https://github.com/superhero-com/matrix-defi-bot/issues/172

### Will you send logs?

Yes

**Comment by michele-franchi** [comment]
@olszewskimar to check during the daily. Should be assigned.
