### ISSUE TITLE
Add “Say Hello” to the wave button

### ISSUE THREAD

**Issue by ifaouibadi** [superhero-com/superhero-chat-web#36]
Add say hello text next to the wave icon.

**Comment by Liubov-crypto** [comment]
Can't see "hello" text. Probably not merged yet...


https://github.com/superhero-com/element-web/assets/69896204/1de663d0-4bfb-4c8d-b4c2-4b08d3f10286

**Comment by Liubov-crypto** [comment]
LGTM
