### ISSUE TITLE
Improve user invitation in TG rooms

### ISSUE THREAD

**Issue by olszewskimar** [superhero-com/superhero-chat-web#40]
### Steps to reproduce

- for private rooms, the default screen should be changed with a hint to interact with the community bot, the minimum threshold, and the number of users

- for public rooms, the bottom section should display a message like “You need to own more than ≥ 1 “test0” tokens to be able to post in this room.” | Get room tokens (community bot interaction)

@onvisions can you pls provide the design and discuss it with @kenodressel

**Comment by paolomolo** [comment]
@kenodressel  please see https://github.com/superhero-com/matrix-defi-bot/issues/187
