### ISSUE TITLE
The onboarding phase should be improved (/home page should have a wizard suggesting connecting the wallet)

### ISSUE THREAD

**Issue by ifaouibadi** [superhero-com/superhero-chat-web#42]
- /home page should have a wizard suggesting connecting the wallet

@onvisions pls provide the designs, ask @michele-franchi for details
Design below is synced with @paolomolo.

![Image](https://github.com/superhero-com/element-web/assets/12225410/8412920c-3629-44db-9a27-1c61112d4834)

**Comment by Liubov-crypto** [comment]
I'm still seeing the old design page, probably not merged yet...


https://github.com/superhero-com/element-web/assets/69896204/810980d3-622b-4e12-a36f-c92107b8a030

**Comment by Liubov-crypto** [comment]
In general LGTM, but space in 2 is missing. @ifaouibadi please check it. 

![Image](https://github.com/superhero-com/element-web/assets/69896204/899d5856-5615-4b8b-8eba-753cdbc315a2)

**Comment by onvisions** [comment]
@Liubov-crypto @ifaouibadi @michele-franchi

I see that the Download extension buttons (Firefox and Chrome) are implemented with different styling compared to the design. I thought it is a change that you had discussed and I was not aware of the change. However I asked @paolomolo (yesterday) and he answered me this: 

![Image](https://github.com/superhero-com/element-web/assets/12225410/084326dd-7fba-4f55-abfc-d34a2e53385e)

Based on this I'd suggest to stick to the design provided. If anything else has been discussed let me know so we are "at the same page".

**Comment by Liubov-crypto** [comment]
If the task has design changes would be nice to have link to Figma @ifaouibadi @onvisions

**Comment by Liubov-crypto** [comment]
LGTM, but the space in Ad2 is still needed.
