### ISSUE TITLE
The user sidebar should display a big “Message” button, instead of the link in options

### ISSUE THREAD

**Issue by ifaouibadi** [superhero-com/superhero-chat-web#43]
@onvisions can you pls provide the design here 

![Image](https://github.com/superhero-com/element-web/assets/12225410/bcb7f429-fb62-409a-96a8-943b127b4c4b)

**FIgma reference:** https://www.figma.com/file/3oGLWzSH0oJljo4RETZtur/Superhero-Wallet-UI-(%E2%9C%94%EF%B8%8FUpdated)?type=design&node-id=29617-174066&mode=design&t=rT0RKzM3vKxT92qG-0

**Comment by onvisions** [comment]
@ifaouibadi Design was provided in the draft and there was a Figma reference link. What additional design do you need? We are talking about the "Send Message" button on the right side panel. The "Message" link from Options list should be removed as the button is performing its purpose just making it more prominent.

![Image](https://github.com/superhero-com/element-web/assets/12225410/8e0a8f49-1f36-459d-8a07-40c7b6dece4f)

**Comment by Liubov-crypto** [comment]
I can't see "Send message" button, probably not implemented yet..



![Image](https://github.com/superhero-com/element-web/assets/69896204/85a91411-7d04-4169-b617-a254894a75c1)

**Comment by Liubov-crypto** [comment]
LGTM
